name: Hadoop Kodo CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        hadoop-version: ["3.1.4", "3.2.4", "3.3.5"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: corretto
          cache: maven

      - name: Generate mock test files
        run: python3 tools/kv_xml_gen.py src/test/resources/auth-keys.xml fs.qiniu.test.useMock true

      - name: Run mock tests and package jar
        run: mvn package test -Dtest="**/ITestQiniuKodo*" -Dhadoop.version=${{ matrix.hadoop-version }}