name: Release hadoop-kodo

on:
  push:
    tags:
      - v*

permissions: write-all

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
          body: |
            Release Notes

  upload_qiniu_sdk_jar:
    name: Upload Qiniu SDK Jar
    runs-on: ubuntu-latest
    needs: create_release
    env:
      QINIU_SDK_JAR: ""
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: corretto
          cache: maven

      - name: Copy dependencies to target
        run: |
          mvn dependency:copy-dependencies
          echo "QINIU_SDK_JAR=$(ls target/dependency | grep ^qiniu)" >> "$GITHUB_ENV"

      - name: Upload Jar to release draft
        id: upload-release-assets-qiniu-sdk-java
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ needs.create_release.outputs.upload_url }}
            asset_path: ./target/dependency/${{ env.QINIU_SDK_JAR }}
            asset_name: ${{ env.QINIU_SDK_JAR }}
            asset_content_type: application/java-archive

  build_and_upload_jar:
    name: Build and Upload Jar
    strategy:
      matrix:
        hadoop-version: [ "3.1.4", "3.2.4", "3.3.5" ]
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Set version by tag
        id: set-version-by-tag
        run: echo ::set-output name=version::${GITHUB_REF#refs/v*/}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: corretto
          cache: maven

      - name: Generate mock test files
        run: python3 tools/kv_xml_gen.py src/test/resources/auth-keys.xml fs.qiniu.test.useMock true

      - name: Run mock tests
        run: mvn package test -Dtest="**/ITestQiniuKodo*" -Dhadoop.version=${{ matrix.hadoop-version }} -Dself.version=${{ steps.set-version-by-tag.outputs.version }}

      - name: Upload Jar to release draft
        id: upload-release-assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ needs.create_release.outputs.upload_url }}
            asset_path: ./target/hadoop-kodo-${{ steps.set-version-by-tag.outputs.version }}.jar
            asset_name: hadoop-kodo-${{ matrix.hadoop-version }}-${{ steps.set-version-by-tag.outputs.version }}.jar
            asset_content_type: application/java-archive