name: Release hadoop-kodo

on:
  workflow_dispatch:
    inputs:
      hadoop-kodo-version:
        description: 'Hadoop Kodo version'
        required: true
        default: '1.0.0'

permissions: write-all

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.hadoop-kodo-version }}
          release_name: Release v${{ github.event.inputs.hadoop-kodo-version }}
          draft: true
          prerelease: false
          body: |
            Release Notes

  build_and_upload_jar:
    name: Build and Upload Jar
    strategy:
      matrix:
        hadoop-version: [ "3.1.4", "3.2.4", "3.3.5" ]
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: corretto
          cache: maven

      - name: Generate mock test files
        run: python3 tools/kv_xml_gen.py src/test/resources/auth-keys.xml fs.qiniu.test.useMock true

      - name: Run mock tests
        run: mvn package test -Dtest="**/ITestQiniuKodo*" -Dhadoop.version=${{ matrix.hadoop-version }} -Dself.version=${{ github.event.inputs.hadoop-kodo-version }}

      - name: Upload Jar to release draft
        id: upload-release-assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ needs.create_release.outputs.upload_url }}
            asset_path: ./target/hadoop-kodo-${{ github.event.inputs.hadoop-kodo-version }}.jar
            asset_name: hadoop-kodo-${{ github.event.inputs.hadoop-kodo-version }}.jar
            asset_content_type: application/java-archive